export const USER_ROLE = {
  ADMIN: 'ADMIN',
  USER: 'USER',
  NORMALUSER: 'NORMALUSER',
  DOCTOR: 'DOCTOR',
  PHARMACY: 'PHARMACY',
  CLINIC: 'CLINIC',
  DIAGNOSTIC_CENTER: 'DIAGNOSTIC_CENTER',
  MEDICAL_TOURISM: 'MEDICAL_TOURISM',
  PLASTIC_SURGERY: 'PLASTIC_SURGERY',
  IN_VITRO_FERTILIZATION: 'IN_VITRO_FERTILIZATION',
  WELLNESS: 'WELLNESS',
} as const;
